#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.ingress.contour_tls_secret
  namespace: #@ data.values.ingress.contour_tls_namespace
data:
  tls.crt: change-me-secret-crt1
  tls.key: change-me-secret-key1
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "learning-center-{}".format(data.values.ingress.contour_tls_secret)
  namespace: #@ data.values.ingress.contour_tls_namespace
data:
  tls.crt: change-me-secret-crt2
  tls.key: change-me-secret-key2
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "cnrs-{}".format(data.values.ingress.contour_tls_secret)
  namespace: #@ data.values.ingress.contour_tls_namespace
data:
  tls.crt: change-me-secret-crt3
  tls.key: change-me-secret-key3
type: kubernetes.io/tls