#@data/values
---
tanzunet:
  username: user@example.com
  password:
ingress:
  domain: example.com
  contour_tls_namespace: tanzu-system-ingress
  contour_tls_secret: contour-tls-delegation-cert
container_registry:
  hostname: harbor.example.com
  username: admin
  password: 
developer_namespace: dev-space
acme:
  email: user@example.com
aws:
  region: eu-central-1
  credentials:
    accessKey: 
    secretKey: 
  zoneId:
gcloud:
  project_name: exampleproject
  zone_name: example.com

rfc2136:
  host: activedirectory.vmw.local
  domain_user: gorkem #username for a domain user which can issue certs
  domain_user_pass: samplepassword #password for domain user
  port: 53 # for external-dns setup.
  zone: example.com # for external-dns setup. must be root domain.
  insecure: true # for external-dns setup. true,false.
  secret: Zey0ypFf09Ov3kGHP+UjP2ueVo5JPlZ/gX3GRvFfokI= # for external-dns setup. no need to set this, if it's insecure #sudo docker run cmd.cat/tsig-keygen tsig-keygen
  secret_alg: hmac-sha256 # for external-dns setup. no need to set this, if it's insecure
  keyname: tsig-key # for external-dns setup. no need to set this, if it's insecure
provider-config:
  dns: rfc2136     # or gcloud-dns,aws,rfc2136
  k8s: tkgs            # or gke,tkgs,tkgm
tap:
  version: 1
  okta:
    status: enable # or disable
    clientId: clientid-value
    clientSecret: clientsecret-value
    audience: https://dev-changeme.okta.com
  integrations:
    status: enable
    github:
      host: github.com
      token: changemetoken
  catalog:
    status: enable
    url_1:
      target: https://github.com/gorkemozlu/tap-blank-catalog/blob/main/blank/catalog-info.yaml