#@ load("@ytt:data", "data")
---
api_ingress:
  fqdn: #@ "api-tas-adapter.{}".format(data.values.ingress.domain)
  tls:
    crt: "PLACEHOLDER"
    key: "PLACEHOLDER"
app_ingress:
  default_domain:  #@ "tas-adapter.{}".format(data.values.ingress.domain)
  tls:
    crt: "PLACEHOLDER"
    key: "PLACEHOLDER"
app_registry_credentials:
    hostname: #@ data.values.container_registry.hostname
    username: #@ data.values.container_registry.username
    password: #@ data.values.container_registry.password    
kpack_image_tag_prefix: #@ "{}/tas-adapter-droplets".format(data.values.container_registry.hostname)
package_registry_base_path: #@ "{}/tas-adapter-packages".format(data.values.container_registry.hostname)
contour_tls_secret: #@ data.values.ingress.contour_tls_secret
contour_tls_namespace: #@ data.values.ingress.contour_tls_namespace