#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "tas-adapter-{}".format(data.values.ingress.contour_tls_secret)
  namespace: #@ data.values.ingress.contour_tls_namespace
data:
  tls.crt: change-me-secret-crt1
  tls.key: change-me-secret-key1
type: kubernetes.io/tls