#@ load("@ytt:data", "data")
---
#@ if/end data.values.tap.version == 1:
apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
#@ if data.values.tap.version == 0.4:
apiVersion: scst-scan.apps.tanzu.vmware.com/v1alpha1
#@ end
kind: ScanPolicy
metadata:
  name: scan-policy
  namespace: #@ data.values.developer_namespace
spec:
  regoFile: |
    package policies

    default isCompliant = false

    # Accepted Values: "Critical", "High", "Medium", "Low", "Negligible", "UnknownSeverity"
    violatingSeverities := ["Critical","High","UnknownSeverity"]
    ignoreCVEs := []

    contains(array, elem) = true {
      array[_] = elem
    } else = false { true }

    isSafe(match) {
      fails := contains(violatingSeverities, match.Ratings.Rating[_].Severity)
      not fails
    }

    isSafe(match) {
      ignore := contains(ignoreCVEs, match.Id)
      ignore
    }

    isCompliant = isSafe(input.currentVulnerability)
